//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPolicyBasedRoute) DeepCopyInto(out *AdminPolicyBasedRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPolicyBasedRoute.
func (in *AdminPolicyBasedRoute) DeepCopy() *AdminPolicyBasedRoute {
	if in == nil {
		return nil
	}
	out := new(AdminPolicyBasedRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminPolicyBasedRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPolicyBasedRouteList) DeepCopyInto(out *AdminPolicyBasedRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdminPolicyBasedRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPolicyBasedRouteList.
func (in *AdminPolicyBasedRouteList) DeepCopy() *AdminPolicyBasedRouteList {
	if in == nil {
		return nil
	}
	out := new(AdminPolicyBasedRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminPolicyBasedRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPolicyBasedRouteSpec) DeepCopyInto(out *AdminPolicyBasedRouteSpec) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]RoutingPolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPolicyBasedRouteSpec.
func (in *AdminPolicyBasedRouteSpec) DeepCopy() *AdminPolicyBasedRouteSpec {
	if in == nil {
		return nil
	}
	out := new(AdminPolicyBasedRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPolicyBasedRouteStatus) DeepCopyInto(out *AdminPolicyBasedRouteStatus) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPolicyBasedRouteStatus.
func (in *AdminPolicyBasedRouteStatus) DeepCopy() *AdminPolicyBasedRouteStatus {
	if in == nil {
		return nil
	}
	out := new(AdminPolicyBasedRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingPolicyMatch) DeepCopyInto(out *RoutingPolicyMatch) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingPolicyMatch.
func (in *RoutingPolicyMatch) DeepCopy() *RoutingPolicyMatch {
	if in == nil {
		return nil
	}
	out := new(RoutingPolicyMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingPolicyNextHop) DeepCopyInto(out *RoutingPolicyNextHop) {
	*out = *in
	if in.NextHopIPs != nil {
		in, out := &in.NextHopIPs, &out.NextHopIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingPolicyNextHop.
func (in *RoutingPolicyNextHop) DeepCopy() *RoutingPolicyNextHop {
	if in == nil {
		return nil
	}
	out := new(RoutingPolicyNextHop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingPolicyRule) DeepCopyInto(out *RoutingPolicyRule) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	in.To.DeepCopyInto(&out.To)
	in.NextHop.DeepCopyInto(&out.NextHop)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingPolicyRule.
func (in *RoutingPolicyRule) DeepCopy() *RoutingPolicyRule {
	if in == nil {
		return nil
	}
	out := new(RoutingPolicyRule)
	in.DeepCopyInto(out)
	return out
}
