/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	ipreservationv1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ipreservation/v1beta1"
)

// IPReservationSpecApplyConfiguration represents a declarative configuration of the IPReservationSpec type for use
// with apply.
type IPReservationSpecApplyConfiguration struct {
	NetworkAttachmentName *string                        `json:"networkAttachmentName,omitempty"`
	IPFamily              *ipreservationv1beta1.IPFamily `json:"ipfamily,omitempty"`
	Count                 *int32                         `json:"count,omitempty"`
}

// IPReservationSpecApplyConfiguration constructs a declarative configuration of the IPReservationSpec type for use with
// apply.
func IPReservationSpec() *IPReservationSpecApplyConfiguration {
	return &IPReservationSpecApplyConfiguration{}
}

// WithNetworkAttachmentName sets the NetworkAttachmentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkAttachmentName field is set to the value of the last call.
func (b *IPReservationSpecApplyConfiguration) WithNetworkAttachmentName(value string) *IPReservationSpecApplyConfiguration {
	b.NetworkAttachmentName = &value
	return b
}

// WithIPFamily sets the IPFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPFamily field is set to the value of the last call.
func (b *IPReservationSpecApplyConfiguration) WithIPFamily(value ipreservationv1beta1.IPFamily) *IPReservationSpecApplyConfiguration {
	b.IPFamily = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *IPReservationSpecApplyConfiguration) WithCount(value int32) *IPReservationSpecApplyConfiguration {
	b.Count = &value
	return b
}
