#
# Dual-pipeline
#

# This include adds all jobs from CI/CD 1.0 pipeline:
include:
  - project: 'sdn/sdn-cicd'
    file: 'gitlab-cicd/ovn-kubernetes-gitlab-ci.yaml'
    ref: 'main'

# ================================================================================
# CI/CD 2.0:
#
# Design idea of CI/CD 2.0 pipelines is following:
# We have one configurable pipeline that is described by two parts:
# 1. preparation part (see below)
# 2. .gitlab/cicd-2-0.yml
#
# Preparation part defines configuration for .gitlab/cicd-2.0.yml.
# For example it defines what parts of pipeline should be run and what
# should be skipped.
#
# Prepared part is different from context where pipeline is started. Following contexts
# supported so far:
# 1. Merge request either from forked or from main repostory
# 2. Forked repository pipeline
# 3. Release pipeline
#

variables:
  sdn_ns: "sdn"
  DISABLE_CICD_2_0: true

# Check that CICD 2.0 pipeline is executed as part of merge request:
# Either from forked repository to sdn/ovn-kubernetes or
# as branch inside sdn/ovn-kubernetes.
.need-run-cicd-2-0-mr:
  rules:
    - if: >
        (  $RUN_CICD_2_0 == "true" && $DISABLE_CICD_2_0 != "true"
        && $CI_PIPELINE_SOURCE == "merge_request_event")

# Checks that CICD 2.0 pipeline is executed from forked repostitory
.need-run-cicd-2-0-forked:
  rules:
    - if: >
        (  $RUN_CICD_2_0 == "true" && $DISABLE_CICD_2_0 != "true"
        && $CI_PIPELINE_SOURCE == "push"
        && $CI_PROJECT_ROOT_NAMESPACE != $sdn_ns)

# Checks that CICD 2.0 pipeline is executed as push to release (protected)
# branch on main repository
.need-run-cicd-2-0-release:
  rules:
    - if: >
        (  $RUN_CICD_2_0 == "true" && $DISABLE_CICD_2_0 != "true"
        && $CI_PIPELINE_SOURCE == "push"
        && $CI_PROJECT_ROOT_NAMESPACE == $sdn_ns
        && $CI_COMMIT_REF_PROTECTED == "true" )

# Check that CICD 2.0 pipeline is executed when triggered from web
.need-run-cicd-2-0-pre-def-tag:
  rules:
    - if: >
        (  $RUN_CICD_2_0 == "true" && $DISABLE_CICD_2_0 != "true"
        && $CI_PIPELINE_SOURCE == "web"
        && $PRE_DEF_TAG != null
        && $PRE_DEF_TAG != "")

# Run check of ovn-k8s triggered by upstream pipelines like
# ovn-nv or ovs-nv.
.need-run-cicd-2-0-ovn-k8s-check:
  rules:
    - if: >
        (  $RUN_CICD_2_0 == "true" && $DISABLE_CICD_2_0 != "true"
        && $CI_PIPELINE_SOURCE == "pipeline"
        && $ovn_kubernetes_action == "check" )

# Checks that CICD 2.0 need to be run.
# Limitation is applied: only run supported pipelines.
.need-run-cicd-2-0:
  rules:
    - if: >
        (  $RUN_CICD_2_0 == "true" && $DISABLE_CICD_2_0 != "true"
        && ( $CI_PIPELINE_SOURCE == "merge_request_event"
          || $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE != $sdn_ns
          || $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == $sdn_ns && $CI_COMMIT_REF_PROTECTED == "true"
          || $CI_PIPELINE_SOURCE == "web" && $PRE_DEF_TAG != null && $PRE_DEF_TAG != ""
          || $CI_PIPELINE_SOURCE == "pipeline" && $ovn_kubernetes_action == "check" ))

# Promote ovn version by modifying hint file.
.need-promote-pkg-version:
  rules:
    - if: >
        $CI_PIPELINE_SOURCE == "pipeline"
        && $ovn_kubernetes_action == "promote"
        && ( $ovn_version != null || $ovs_version != null )
        && $promote_dry_run != null

.cicd-2-0-allow-failure:
  allow_failure: false

# Prepare data for merge request CI/CD 2.0 pipeline
cicd-2-0:prepare-mr:
  stage: Init-pipeline
  needs: []
  extends:
    - .cicd-2-0-allow-failure
    - .need-run-cicd-2-0-mr
  script:
    - ovn_version=`yq -r '.buildOvnKubernetes.OVN.pkgTag' ./cicd-nv-ovn-kubernetes.yaml`
    - ovs_version=`yq -r '.buildOvnKubernetes.OVS.pkgTag' ./cicd-nv-ovn-kubernetes.yaml`
    - run_check=`yq -r '.cicd.skip_all_checks != true' ./cicd-nv-ovn-kubernetes.yaml`
    - run_unit_tests=`yq -r '(.cicd.skip_make_check != true) and (.cicd.skip_all_checks != true)' ./cicd-nv-ovn-kubernetes.yaml`
    - run_gitops=`yq -r '.cicd.skip_CICD_deploy_and_tests != true' ./cicd-nv-ovn-kubernetes.yaml`
    - gitops_config_run_flow_tests=`yq -r '.cicd.skip_flowTests != true' ./cicd-nv-ovn-kubernetes.yaml`
    - gitops_config_run_cicd_tests=`yq -r '.cicd.skip_SDN_tests != true' ./cicd-nv-ovn-kubernetes.yaml`
    - gitops_config_test_ovn_ic_mode=`yq -r '(.cicd.ovn_mode == null) or (.cicd.ovn_mode == "both") or (.cicd.ovn_mode == "ic")' ./cicd-nv-ovn-kubernetes.yaml`
    - gitops_config_test_ovn_central_mode=`yq -r '(.cicd.ovn_mode == null) or (.cicd.ovn_mode == "both") or (.cicd.ovn_mode == "central")' ./cicd-nv-ovn-kubernetes.yaml`
    - gitops_config_flow_tests_repo_path=`yq -r ".test.flowTests.repo" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_config_flow_tests_repo_branch=`yq -r ".test.flowTests.branch" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - |
      gitops_config=$(jq -c <<EOF
      {
        "runFlowTests": ${gitops_config_run_flow_tests},
        "runCiCdTests": ${gitops_config_run_cicd_tests},
        "flowTests": {
           "repoPath": "${gitops_config_flow_tests_repo_path}",
           "branch": "${gitops_config_flow_tests_repo_branch}"
        },
        "testOvnIcMode": ${gitops_config_test_ovn_ic_mode},
        "testOvnCentralMode": ${gitops_config_test_ovn_central_mode}
      }
      EOF
      )
    - gitops_helm_repo=`yq -r ".deploy.helm.ovn-kubernetes.repo" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_branch=`yq -r ".deploy.helm.ovn-kubernetes.branch" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_values_yaml=`yq -r ".deploy.helm.ovn-kubernetes.values_yaml" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    # Check if HELM_MR_<X> label is used to identify helm repository merge request that
    # should be used for testing.
    - gitops_helm_need_merge=false
    - gitops_helm_need_merge_id=0
    - |
      if helm_mr_id=$(echo ${CI_MERGE_REQUEST_LABELS} | tr ',' '\n' | grep HELM_MR | awk -F_ '{print $NF}' ) ; then
        echo "Helm merge request id: ${helm_mr_id}"
        gitops_helm_need_merge=true
        gitops_helm_need_merge_id=${helm_mr_id}
      fi
    - run_kind_e2e_tests=`yq -r '.cicd.skip_CICD_deploy_and_tests != true' ./cicd-nv-ovn-kubernetes.yaml`
    # Handle pipeline customization via merge request message:
    - |
      cat > ./.gitlab/_pipeline_customization.txt <<EOF
      $CI_MERGE_REQUEST_DESCRIPTION
      EOF
    - run_gitops=`awk -v query=run_gitops -v default_value=${run_gitops} -f ./.gitlab/pipeline_customization.awk ./.gitlab/_pipeline_customization.txt`
    - run_kind_e2e_tests=`awk -v query=run_kind_e2e_tests -v default_value=${run_kind_e2e_tests} -f ./.gitlab/pipeline_customization.awk ./.gitlab/_pipeline_customization.txt`
    - run_check=`awk -v query=run_check -v default_value=${run_check} -f ./.gitlab/pipeline_customization.awk ./.gitlab/_pipeline_customization.txt`
    - run_unit_tests=`awk -v query=run_unit_tests -v default_value=${run_unit_tests} -f ./.gitlab/pipeline_customization.awk ./.gitlab/_pipeline_customization.txt`
    - image_tag=$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    - |
      cat > ./cicd-2-0-trigger.yaml <<EOF
      include:
        local: .gitlab/cicd-2-0.yml
        inputs:
          ovn_version: ${ovn_version}
          ovs_version: ${ovs_version}
          image_tag: ${image_tag}
          run_check: ${run_check}
          run_unit_tests: ${run_unit_tests}
          run_build_and_sign: true
          run_gitops: ${run_gitops}
          gitops_config: '${gitops_config}'
          gitops_helm_repo: ${gitops_helm_repo}
          gitops_helm_branch: ${gitops_helm_branch}
          gitops_helm_values_yaml: ${gitops_helm_values_yaml}
          gitops_helm_chart_version: 0.0.1-${CI_COMMIT_SHORT_SHA}.${CI_PIPELINE_ID}
          gitops_helm_need_merge: ${gitops_helm_need_merge}
          gitops_helm_need_merge_id: ${gitops_helm_need_merge_id}
          run_kind_e2e_tests: ${run_kind_e2e_tests}
          kind_e2e_project_name: $CI_PROJECT_NAME
          kind_e2e_project_path: $CI_PROJECT_PATH
          kind_e2e_repo_branch: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
          kind_e2e_repo_commit_sha: $CI_COMMIT_SHA
          kind_e2e_mode: MERGE
          kind_e2e_merge_request_id: $CI_MERGE_REQUEST_IID
          promote_helm: false
          promote_helm_branch: .not-defined
          latest_tag: .not-defined
          email_message_description: |
              $GITLAB_USER_NAME just built and pushed ovnkube
              CommitID: $CI_COMMIT_SHORT_SHA
              Pipeline URL: $CI_PIPELINE_URL
              Merge request: $CI_MERGE_REQUEST_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID
      EOF
    - cat ./cicd-2-0-trigger.yaml
  artifacts:
    paths:
      - cicd-2-0-trigger.yaml

# Prepare data for forked repository CI/CD 2.0 pipeline
cicd-2-0:prepare-fork:
  stage: Init-pipeline
  needs: []
  extends:
    - .cicd-2-0-allow-failure
    - .need-run-cicd-2-0-forked
  script:
    - |
      cat > ./cicd-2-0-trigger.yaml <<EOF
      include:
        local: .gitlab/cicd-2-0.yml
        inputs:
          ovn_version: .not-defined
          ovs_version: .not-defined
          image_tag: .not-defined
          run_check: true
          run_unit_tests: true
          run_build_and_sign: false
          run_gitops: false
          run_kind_e2e_tests: false
          force_instance_runners: true
          kind_e2e_project_name: .not-defined
          kind_e2e_project_path: .not-defined
          kind_e2e_repo_branch: .not-defined
          kind_e2e_repo_commit_sha: .not-defined
          promote_helm: false
          promote_helm_branch: .not-defined
          latest_tag: .not-defined
      EOF
    - cat ./cicd-2-0-trigger.yaml
  artifacts:
    paths:
      - cicd-2-0-trigger.yaml

# Prepare data for merge request CI/CD 2.0 pipeline
cicd-2-0:prepare-release:
  stage: Init-pipeline
  needs: []
  extends:
    - .cicd-2-0-allow-failure
    - .need-run-cicd-2-0-release
  script:
    - ovn_version=`yq -r '.buildOvnKubernetes.OVN.pkgTag' ./cicd-nv-ovn-kubernetes.yaml`
    - ovs_version=`yq -r '.buildOvnKubernetes.OVS.pkgTag' ./cicd-nv-ovn-kubernetes.yaml`
    - image_tag=$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    - gitops_config_test_ovn_ic_mode=`yq -r '(.cicd.ovn_mode == null) or (.cicd.ovn_mode == "both") or (.cicd.ovn_mode == "ic")' ./cicd-nv-ovn-kubernetes.yaml`
    - gitops_config_test_ovn_central_mode=`yq -r '(.cicd.ovn_mode == null) or (.cicd.ovn_mode == "both") or (.cicd.ovn_mode == "central")' ./cicd-nv-ovn-kubernetes.yaml`
    - gitops_config_flow_tests_repo_path=`yq -r ".test.flowTests.repo" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_config_flow_tests_repo_branch=`yq -r ".test.flowTests.branch" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - |
      gitops_config=$(jq -c <<EOF
      {
        "runFlowTests": true,
        "runCiCdTests": true,
        "flowTests": {
           "repoPath": "${gitops_config_flow_tests_repo_path}",
           "branch": "${gitops_config_flow_tests_repo_branch}"
        },
        "testOvnIcMode": ${gitops_config_test_ovn_ic_mode},
        "testOvnCentralMode": ${gitops_config_test_ovn_central_mode}
      }
      EOF
      )
    - gitops_helm_repo=`yq -r ".deploy.helm.ovn-kubernetes.repo" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_branch=`yq -r ".deploy.helm.ovn-kubernetes.branch" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_values_yaml=`yq -r ".deploy.helm.ovn-kubernetes.values_yaml" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_need_merge=false
    - gitops_helm_need_merge_id=0
    - promote_helm=`yq -r '.artifacts.promote == "yes"' ./cicd-nv-ovn-kubernetes.yaml`
    - promote_helm_repo=`yq -r ".artifacts.helm.repo"  ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - promote_helm_branch=`yq -r ".artifacts.helm.branch"  ./cicd-nv-ovn-kubernetes.yaml`
    - promote_helm_values_yaml=`yq -r ".artifacts.helm.values_yaml"  ./cicd-nv-ovn-kubernetes.yaml`
    - promote_helm_need_merge=false
    - promote_helm_need_merge_id=0
    - latest_tag=`yq -r ".artifacts.latestImageNameTag" ./cicd-nv-ovn-kubernetes.yaml`
    - git log -1 --pretty=%B
    - |
      if msg_merge_id=$(git log -1 --pretty=%B | grep "See merge request" | awk -F! '{print $2}') ; then
        echo "Merge request id: ${msg_merge_id}"
        if helm_mr_id=$(curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$msg_merge_id" | jq '.labels' | grep HELM_MR | tr -d '"' | awk -F_ '{print $NF}') ; then
          echo "Helm merge request id: ${helm_mr_id}"
          promote_helm_need_merge=true
          promote_helm_need_merge_id=${helm_mr_id}
          gitops_helm_need_merge=true
          gitops_helm_need_merge_id=${helm_mr_id}
        fi
      fi
    - |
      cat > ./cicd-2-0-trigger.yaml <<EOF
      include:
        local: .gitlab/cicd-2-0.yml
        inputs:
          ovn_version: ${ovn_version}
          ovs_version: ${ovs_version}
          image_tag: ${image_tag}
          run_check: true
          run_unit_tests: true
          run_build_and_sign: true
          run_gitops: true
          gitops_config: '${gitops_config}'
          gitops_helm_repo: ${gitops_helm_repo}
          gitops_helm_branch: ${gitops_helm_branch}
          gitops_helm_values_yaml: ${gitops_helm_values_yaml}
          gitops_helm_chart_version: 0.0.1-${CI_COMMIT_SHORT_SHA}.${CI_PIPELINE_ID}
          gitops_helm_need_merge: ${gitops_helm_need_merge}
          gitops_helm_need_merge_id: ${gitops_helm_need_merge_id}
          run_kind_e2e_tests: true
          kind_e2e_project_name: $CI_PROJECT_NAME
          kind_e2e_project_path: $CI_PROJECT_PATH
          kind_e2e_repo_branch: $CI_COMMIT_BRANCH
          kind_e2e_repo_commit_sha: $CI_COMMIT_SHA
          promote_helm: ${promote_helm}
          promote_helm_repo: ${promote_helm_repo}
          promote_helm_branch: ${promote_helm_branch}
          promote_helm_values_yaml: ${promote_helm_values_yaml}
          promote_helm_dry_run: ${RUN_CICD_1_0:-"false"}
          promote_helm_need_merge: ${promote_helm_need_merge}
          promote_helm_need_merge_id: ${promote_helm_need_merge_id}
          latest_tag: ${latest_tag}
          tag_latest_dry_run: ${RUN_CICD_1_0:-"false"}
      EOF
    - cat ./cicd-2-0-trigger.yaml
  artifacts:
    paths:
      - cicd-2-0-trigger.yaml

# Prepare data for web trggered CI/CD 2.0 pipeline with PRE_DEF_TAG
cicd-2-0:prepare-pre-def-tag:
  stage: Init-pipeline
  needs: []
  extends:
    - .cicd-2-0-allow-failure
    - .need-run-cicd-2-0-pre-def-tag
  script:
    # Handle pipeline customization via merge request message:
    - image_tag=$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    - gitops_helm_repo=`yq -r ".deploy.helm.ovn-kubernetes.repo" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_branch=`yq -r ".deploy.helm.ovn-kubernetes.branch" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_values_yaml=`yq -r ".deploy.helm.ovn-kubernetes.values_yaml" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_need_merge=false
    - |
      if [[ ! -z $PRE_DEF_TAG ]] ; then
        echo "Using pre defined tag $PRE_DEF_TAG"
        echo "disable unit test checks and build"
        run_check=false
        run_build_and_sign=false
        image_tag=$PRE_DEF_TAG
      fi
    - |
      cat > ./cicd-2-0-trigger.yaml <<EOF
      include:
        local: .gitlab/cicd-2-0.yml
        inputs:
          ovn_version: .not-defined
          ovs_version: .not-defined
          image_tag: ${PRE_DEF_TAG}
          run_check: false
          run_unit_tests: false
          run_build_and_sign: false
          run_gitops: true
          gitops_helm_repo: ${gitops_helm_repo}
          gitops_helm_branch: ${gitops_helm_branch}
          gitops_helm_values_yaml: ${gitops_helm_values_yaml}
          gitops_helm_chart_version: 0.0.1-${CI_COMMIT_SHORT_SHA}.${CI_PIPELINE_ID}
          run_kind_e2e_tests: true
          kind_e2e_project_name: $CI_PROJECT_NAME
          kind_e2e_project_path: $CI_PROJECT_PATH
          kind_e2e_repo_branch: $CI_COMMIT_BRANCH
          kind_e2e_repo_commit_sha: $CI_COMMIT_SHA
          promote_helm: false
          promote_helm_branch: .not-defined
          latest_tag: .not-defined
      EOF
    - cat ./cicd-2-0-trigger.yaml
  artifacts:
    paths:
      - cicd-2-0-trigger.yaml

# Prepare data for upstream triggered check pipelines
cicd-2-0:prepare-check:
  stage: Init-pipeline
  needs: []
  extends:
    - .cicd-2-0-allow-failure
    - .need-run-cicd-2-0-ovn-k8s-check
  script:
    # Get default ovn / ovs from cicd-nv-ovn-kubernetes.yaml
    - ovn_version=${ovn_version:-`yq -r '.buildOvnKubernetes.OVN.pkgTag' ./cicd-nv-ovn-kubernetes.yaml`}
    - ovs_version=${ovs_version:-`yq -r '.buildOvnKubernetes.OVS.pkgTag' ./cicd-nv-ovn-kubernetes.yaml`}
    - run_gitops=${run_gitops:-true}
    - gitops_branch=${gitops_branch:-""}
    - gitops_config=${gitops_config:-"{}"}
    - gitops_helm_repo=`yq -r ".deploy.helm.ovn-kubernetes.repo" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_branch=`yq -r ".deploy.helm.ovn-kubernetes.branch" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_values_yaml=`yq -r ".deploy.helm.ovn-kubernetes.values_yaml" ./cicd-nv-ovn-kubernetes.yaml | sed "s/ssh:\/\/[^\/]*\///" | sed "s/.git$//"`
    - gitops_helm_need_merge=false
    - run_check=${run_check:-true}
    - run_unit_tests=${run_unit_tests:-true}
    - run_kind_e2e_tests=${run_kind_e2e_tests:-true}
    - image_tag=${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}
    - |
      if [[ $run_kind_e2e_tests == "true" ]] ; then
          kind_e2e_project_name=${kind_e2e_project_name:?"kind_e2e_project_name is required"}
          kind_e2e_project_path=${kind_e2e_project_path:?"kind_e2e_project_path is required"}
          kind_e2e_repo_branch=${kind_e2e_repo_branch:?"kind_e2e_project_branch is required"}
          kind_e2e_repo_commit_sha=${kind_e2e_repo_commit_sha:?"kind_e2e_project_sha is required"}
      else
          kind_e2e_project_name=${kind_e2e_project_name:-".not-defined"}
          kind_e2e_project_path=${kind_e2e_project_path:-".not-defined"}
          kind_e2e_repo_branch=${kind_e2e_repo_branch:-".not-defined"}
          kind_e2e_repo_commit_sha=${kind_e2e_repo_commit_sha:-".not-defined"}
      fi
    - |
      cat > ./cicd-2-0-trigger.yaml <<EOF
      include:
        local: .gitlab/cicd-2-0.yml
        inputs:
          ovn_version: ${ovn_version}
          ovs_version: ${ovs_version}
          image_tag: ${image_tag}
          run_check: ${run_check}
          run_unit_tests: ${run_unit_tests}
          run_build_and_sign: true
          run_gitops: ${run_gitops}
          gitops_branch: ${gitops_branch}
          gitops_config: '${gitops_config}'
          gitops_helm_repo: ${gitops_helm_repo}
          gitops_helm_branch: ${gitops_helm_branch}
          gitops_helm_values_yaml: ${gitops_helm_values_yaml}
          gitops_helm_chart_version: 0.0.1-${CI_COMMIT_SHORT_SHA}.${CI_PIPELINE_ID}
          run_kind_e2e_tests: ${run_kind_e2e_tests}
          kind_e2e_project_name: ${kind_e2e_project_name}
          kind_e2e_project_path: ${kind_e2e_project_path}
          kind_e2e_repo_branch: ${kind_e2e_repo_branch}
          kind_e2e_repo_commit_sha: ${kind_e2e_repo_commit_sha}
          promote_helm: false
          promote_helm_branch: .not-defined
          latest_tag: .not-defined
      EOF
    - cat ./cicd-2-0-trigger.yaml
  artifacts:
    paths:
      - cicd-2-0-trigger.yaml

# Collect artifacts from prepare phase to pass
# it to triggered pipeline. Prepare phase can be one
# but in this case it should contain all options together
# and it is much harder to follow
cicd-2-0:prepare:
  stage: Init-pipeline
  extends:
    - .cicd-2-0-allow-failure
    - .need-run-cicd-2-0
  needs:
    - job: cicd-2-0:prepare-fork
      optional: true
    - job: cicd-2-0:prepare-mr
      optional: true
    - job: cicd-2-0:prepare-release
      optional: true
    - job: cicd-2-0:prepare-pre-def-tag
      optional: true
    - job: cicd-2-0:prepare-check
      optional: true
  script:
    - cat cicd-2-0-trigger.yaml
  artifacts:
    paths:
      - cicd-2-0-trigger.yaml

cicd-2-0:
  stage: .post
  extends:
    - .cicd-2-0-allow-failure
    - .need-run-cicd-2-0
  needs:
    - cicd-2-0:prepare
  trigger:
    strategy: depend
    include:
      - artifact: cicd-2-0-trigger.yaml
        job: cicd-2-0:prepare

cicd-2-0:promote-pkg-version:
  stage: Init-pipeline
  variables:
    GIT_STRATEGY: clone
  extends:
    - .need-promote-pkg-version
  script:
    - ovn_kubernetes_cicd_yaml=./cicd-nv-ovn-kubernetes.yaml
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git checkout ${CI_COMMIT_BRANCH}
    - message=""
    - |
      if [[ ! -z ${ovn_version} ]] ; then
        echo yq eval -i "(.buildOvnKubernetes.OVN.pkgTag = \"${ovn_version}\")" ${ovn_kubernetes_cicd_yaml}
        yq eval -i "(.buildOvnKubernetes.OVN.pkgTag = \"${ovn_version}\")" ${ovn_kubernetes_cicd_yaml}
        message=" new ovn version: ${ovn_version};"
      fi
    - |
      if [[ ! -z ${ovs_version} ]] ; then
        echo yq eval -i "(.buildOvnKubernetes.OVS.pkgTag = \"${ovs_version}\")" ${ovn_kubernetes_cicd_yaml}
        yq eval -i "(.buildOvnKubernetes.OVS.pkgTag = \"${ovs_version}\")" ${ovn_kubernetes_cicd_yaml}
        message="${message} new ovs version: ${ovs_version};"
      fi
    - |
      if [ -n "$(git status --porcelain)" ]; then
         git diff
         git add $ovn_kubernetes_cicd_yaml
         git commit -m "SDN CICD:${message}"
         # if this push fails because of 403 then you probably need to
         # give permissions to the job to push to repository:
         # Settings > Job token permissions > Allow Git push to the repository
         if [ $promote_dry_run != "true" ] ; then
            git push
         else
            echo "DRY RUN: git push"
         fi
      else
         echo "Nothing has changed"
      fi
