version = "1.0.0"

[oss]

[[oss.excluded.directories]]
paths = ['test/e2e/vendor/k8s.io/apimachinery/pkg/', 'test/e2e/vendor/k8s.io/api/', 'go-controller/vendor/k8s.io/apimachinery/pkg/', 'go-controller/vendor/k8s.io/api/']
comment = 'Exclude Podman package repos'

[[oss.excluded.directories]]
paths = ['vendor/github.com/vishvananda/', 'test/e2e/vendor/google.golang.org/protobuf/', 'go-controller/vendor/google.golang.org/protobuf/', 'go-controller/vendor/github.com/cpuguy83/']
comment = 'Exclude runc package repos'

