version = "1.0.0"

[oss]

[[oss.excluded.directories]]
paths = ['test/e2e/vendor/k8s.io/apimachinery/pkg/', 'test/e2e/vendor/k8s.io/api/', 'go-controller/vendor/k8s.io/apimachinery/pkg/', 'go-controller/vendor/k8s.io/api/']
comment = 'Exclude Podman package repos'

