//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorSinkDevice) DeepCopyInto(out *MirrorSinkDevice) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorSinkDevice.
func (in *MirrorSinkDevice) DeepCopy() *MirrorSinkDevice {
	if in == nil {
		return nil
	}
	out := new(MirrorSinkDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMirror) DeepCopyInto(out *PortMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMirror.
func (in *PortMirror) DeepCopy() *PortMirror {
	if in == nil {
		return nil
	}
	out := new(PortMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMirrorList) DeepCopyInto(out *PortMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PortMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMirrorList.
func (in *PortMirrorList) DeepCopy() *PortMirrorList {
	if in == nil {
		return nil
	}
	out := new(PortMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMirrorSinkLocal) DeepCopyInto(out *PortMirrorSinkLocal) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	out.DeviceInfo = in.DeviceInfo
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMirrorSinkLocal.
func (in *PortMirrorSinkLocal) DeepCopy() *PortMirrorSinkLocal {
	if in == nil {
		return nil
	}
	out := new(PortMirrorSinkLocal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMirrorSource) DeepCopyInto(out *PortMirrorSource) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	if in.NetworkAttachmentName != nil {
		in, out := &in.NetworkAttachmentName, &out.NetworkAttachmentName
		*out = make([]NetworkAttachmentNameString, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMirrorSource.
func (in *PortMirrorSource) DeepCopy() *PortMirrorSource {
	if in == nil {
		return nil
	}
	out := new(PortMirrorSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMirrorSpec) DeepCopyInto(out *PortMirrorSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]PortMirrorSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.SinkLocal.DeepCopyInto(&out.SinkLocal)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMirrorSpec.
func (in *PortMirrorSpec) DeepCopy() *PortMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(PortMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortMirrorStatus) DeepCopyInto(out *PortMirrorStatus) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortMirrorStatus.
func (in *PortMirrorStatus) DeepCopy() *PortMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(PortMirrorStatus)
	in.DeepCopyInto(out)
	return out
}
