/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	adminpbrv1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1"
	versioned "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1/apis/clientset/versioned"
	internalinterfaces "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1/apis/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1/apis/listers/adminpbr/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AdminPolicyBasedRouteInformer provides access to a shared informer and lister for
// AdminPolicyBasedRoutes.
type AdminPolicyBasedRouteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.AdminPolicyBasedRouteLister
}

type adminPolicyBasedRouteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAdminPolicyBasedRouteInformer constructs a new informer for AdminPolicyBasedRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAdminPolicyBasedRouteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAdminPolicyBasedRouteInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAdminPolicyBasedRouteInformer constructs a new informer for AdminPolicyBasedRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAdminPolicyBasedRouteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1beta1().AdminPolicyBasedRoutes().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1beta1().AdminPolicyBasedRoutes().Watch(context.TODO(), options)
			},
		},
		&adminpbrv1beta1.AdminPolicyBasedRoute{},
		resyncPeriod,
		indexers,
	)
}

func (f *adminPolicyBasedRouteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAdminPolicyBasedRouteInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *adminPolicyBasedRouteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&adminpbrv1beta1.AdminPolicyBasedRoute{}, f.defaultInformer)
}

func (f *adminPolicyBasedRouteInformer) Lister() v1beta1.AdminPolicyBasedRouteLister {
	return v1beta1.NewAdminPolicyBasedRouteLister(f.Informer().GetIndexer())
}
