/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	types "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/types"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VirtualIPStatusApplyConfiguration represents a declarative configuration of the VirtualIPStatus type for use
// with apply.
type VirtualIPStatusApplyConfiguration struct {
	ActivePod          *v1.ObjectReference  `json:"activePod,omitempty"`
	LastTransitionTime *metav1.Time         `json:"lastTransitionTime,omitempty"`
	BackingPods        []v1.ObjectReference `json:"backingPods,omitempty"`
	Messages           []string             `json:"messages,omitempty"`
	Status             *types.OvnK8sStatus  `json:"status,omitempty"`
}

// VirtualIPStatusApplyConfiguration constructs a declarative configuration of the VirtualIPStatus type for use with
// apply.
func VirtualIPStatus() *VirtualIPStatusApplyConfiguration {
	return &VirtualIPStatusApplyConfiguration{}
}

// WithActivePod sets the ActivePod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActivePod field is set to the value of the last call.
func (b *VirtualIPStatusApplyConfiguration) WithActivePod(value v1.ObjectReference) *VirtualIPStatusApplyConfiguration {
	b.ActivePod = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *VirtualIPStatusApplyConfiguration) WithLastTransitionTime(value metav1.Time) *VirtualIPStatusApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}

// WithBackingPods adds the given value to the BackingPods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BackingPods field.
func (b *VirtualIPStatusApplyConfiguration) WithBackingPods(values ...v1.ObjectReference) *VirtualIPStatusApplyConfiguration {
	for i := range values {
		b.BackingPods = append(b.BackingPods, values[i])
	}
	return b
}

// WithMessages adds the given value to the Messages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Messages field.
func (b *VirtualIPStatusApplyConfiguration) WithMessages(values ...string) *VirtualIPStatusApplyConfiguration {
	for i := range values {
		b.Messages = append(b.Messages, values[i])
	}
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *VirtualIPStatusApplyConfiguration) WithStatus(value types.OvnK8sStatus) *VirtualIPStatusApplyConfiguration {
	b.Status = &value
	return b
}
