/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// VirtualIPSpecApplyConfiguration represents a declarative configuration of the VirtualIPSpec type for use
// with apply.
type VirtualIPSpecApplyConfiguration struct {
	VirtualIP             *string                             `json:"virtualIP,omitempty"`
	PodSelector           *v1.LabelSelectorApplyConfiguration `json:"podSelector,omitempty"`
	NetworkAttachmentName *string                             `json:"networkAttachmentName,omitempty"`
}

// VirtualIPSpecApplyConfiguration constructs a declarative configuration of the VirtualIPSpec type for use with
// apply.
func VirtualIPSpec() *VirtualIPSpecApplyConfiguration {
	return &VirtualIPSpecApplyConfiguration{}
}

// WithVirtualIP sets the VirtualIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VirtualIP field is set to the value of the last call.
func (b *VirtualIPSpecApplyConfiguration) WithVirtualIP(value string) *VirtualIPSpecApplyConfiguration {
	b.VirtualIP = &value
	return b
}

// WithPodSelector sets the PodSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSelector field is set to the value of the last call.
func (b *VirtualIPSpecApplyConfiguration) WithPodSelector(value *v1.LabelSelectorApplyConfiguration) *VirtualIPSpecApplyConfiguration {
	b.PodSelector = value
	return b
}

// WithNetworkAttachmentName sets the NetworkAttachmentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkAttachmentName field is set to the value of the last call.
func (b *VirtualIPSpecApplyConfiguration) WithNetworkAttachmentName(value string) *VirtualIPSpecApplyConfiguration {
	b.NetworkAttachmentName = &value
	return b
}
