/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	networkprobev1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
)

// DNSProbeApplyConfiguration represents a declarative configuration of the DNSProbe type for use
// with apply.
type DNSProbeApplyConfiguration struct {
	LookupName *string                       `json:"lookupName,omitempty"`
	IPAddress  *string                       `json:"ipAddress,omitempty"`
	NameServer *string                       `json:"nameServer,omitempty"`
	Interval   *networkprobev1beta1.Duration `json:"interval,omitempty"`
	PacketSpec *PacketSpecApplyConfiguration `json:"packetSpec,omitempty"`
}

// DNSProbeApplyConfiguration constructs a declarative configuration of the DNSProbe type for use with
// apply.
func DNSProbe() *DNSProbeApplyConfiguration {
	return &DNSProbeApplyConfiguration{}
}

// WithLookupName sets the LookupName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LookupName field is set to the value of the last call.
func (b *DNSProbeApplyConfiguration) WithLookupName(value string) *DNSProbeApplyConfiguration {
	b.LookupName = &value
	return b
}

// WithIPAddress sets the IPAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPAddress field is set to the value of the last call.
func (b *DNSProbeApplyConfiguration) WithIPAddress(value string) *DNSProbeApplyConfiguration {
	b.IPAddress = &value
	return b
}

// WithNameServer sets the NameServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NameServer field is set to the value of the last call.
func (b *DNSProbeApplyConfiguration) WithNameServer(value string) *DNSProbeApplyConfiguration {
	b.NameServer = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *DNSProbeApplyConfiguration) WithInterval(value networkprobev1beta1.Duration) *DNSProbeApplyConfiguration {
	b.Interval = &value
	return b
}

// WithPacketSpec sets the PacketSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketSpec field is set to the value of the last call.
func (b *DNSProbeApplyConfiguration) WithPacketSpec(value *PacketSpecApplyConfiguration) *DNSProbeApplyConfiguration {
	b.PacketSpec = value
	return b
}
