/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	networkprobev1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
)

// HTTPProbeApplyConfiguration represents a declarative configuration of the HTTPProbe type for use
// with apply.
type HTTPProbeApplyConfiguration struct {
	URL        *string                       `json:"url,omitempty"`
	TLSConfig  *TLSConfigApplyConfiguration  `json:"tlsConfig,omitempty"`
	Interval   *networkprobev1beta1.Duration `json:"interval,omitempty"`
	PacketSpec *PacketSpecApplyConfiguration `json:"packetSpec,omitempty"`
	Headers    map[string]string             `json:"headers,omitempty"`
	Method     *string                       `json:"method,omitempty"`
}

// HTTPProbeApplyConfiguration constructs a declarative configuration of the HTTPProbe type for use with
// apply.
func HTTPProbe() *HTTPProbeApplyConfiguration {
	return &HTTPProbeApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *HTTPProbeApplyConfiguration) WithURL(value string) *HTTPProbeApplyConfiguration {
	b.URL = &value
	return b
}

// WithTLSConfig sets the TLSConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSConfig field is set to the value of the last call.
func (b *HTTPProbeApplyConfiguration) WithTLSConfig(value *TLSConfigApplyConfiguration) *HTTPProbeApplyConfiguration {
	b.TLSConfig = value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *HTTPProbeApplyConfiguration) WithInterval(value networkprobev1beta1.Duration) *HTTPProbeApplyConfiguration {
	b.Interval = &value
	return b
}

// WithPacketSpec sets the PacketSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketSpec field is set to the value of the last call.
func (b *HTTPProbeApplyConfiguration) WithPacketSpec(value *PacketSpecApplyConfiguration) *HTTPProbeApplyConfiguration {
	b.PacketSpec = value
	return b
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *HTTPProbeApplyConfiguration) WithHeaders(entries map[string]string) *HTTPProbeApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *HTTPProbeApplyConfiguration) WithMethod(value string) *HTTPProbeApplyConfiguration {
	b.Method = &value
	return b
}
