/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NetworkProbeSpecApplyConfiguration represents a declarative configuration of the NetworkProbeSpec type for use
// with apply.
type NetworkProbeSpecApplyConfiguration struct {
	NodeSelector    *v1.LabelSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
	Interval        *v1beta1.Duration                   `json:"interval,omitempty"`
	Suspend         *bool                               `json:"suspend,omitempty"`
	DNSProbes       []DNSProbeApplyConfiguration        `json:"dnsProbes,omitempty"`
	HTTPProbes      []HTTPProbeApplyConfiguration       `json:"httpProbes,omitempty"`
	TCPProbes       []TCPProbeApplyConfiguration        `json:"tcpProbes,omitempty"`
	UDPStreamProbes []UDPStreamProbeApplyConfiguration  `json:"udpStreamProbes,omitempty"`
}

// NetworkProbeSpecApplyConfiguration constructs a declarative configuration of the NetworkProbeSpec type for use with
// apply.
func NetworkProbeSpec() *NetworkProbeSpecApplyConfiguration {
	return &NetworkProbeSpecApplyConfiguration{}
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *NetworkProbeSpecApplyConfiguration) WithNodeSelector(value *v1.LabelSelectorApplyConfiguration) *NetworkProbeSpecApplyConfiguration {
	b.NodeSelector = value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *NetworkProbeSpecApplyConfiguration) WithInterval(value v1beta1.Duration) *NetworkProbeSpecApplyConfiguration {
	b.Interval = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *NetworkProbeSpecApplyConfiguration) WithSuspend(value bool) *NetworkProbeSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithDNSProbes adds the given value to the DNSProbes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DNSProbes field.
func (b *NetworkProbeSpecApplyConfiguration) WithDNSProbes(values ...*DNSProbeApplyConfiguration) *NetworkProbeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDNSProbes")
		}
		b.DNSProbes = append(b.DNSProbes, *values[i])
	}
	return b
}

// WithHTTPProbes adds the given value to the HTTPProbes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HTTPProbes field.
func (b *NetworkProbeSpecApplyConfiguration) WithHTTPProbes(values ...*HTTPProbeApplyConfiguration) *NetworkProbeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHTTPProbes")
		}
		b.HTTPProbes = append(b.HTTPProbes, *values[i])
	}
	return b
}

// WithTCPProbes adds the given value to the TCPProbes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TCPProbes field.
func (b *NetworkProbeSpecApplyConfiguration) WithTCPProbes(values ...*TCPProbeApplyConfiguration) *NetworkProbeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTCPProbes")
		}
		b.TCPProbes = append(b.TCPProbes, *values[i])
	}
	return b
}

// WithUDPStreamProbes adds the given value to the UDPStreamProbes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UDPStreamProbes field.
func (b *NetworkProbeSpecApplyConfiguration) WithUDPStreamProbes(values ...*UDPStreamProbeApplyConfiguration) *NetworkProbeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUDPStreamProbes")
		}
		b.UDPStreamProbes = append(b.UDPStreamProbes, *values[i])
	}
	return b
}
