/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	networkprobev1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
)

// TCPProbeApplyConfiguration represents a declarative configuration of the TCPProbe type for use
// with apply.
type TCPProbeApplyConfiguration struct {
	Host       *string                       `json:"host,omitempty"`
	Port       *int32                        `json:"port,omitempty"`
	Interval   *networkprobev1beta1.Duration `json:"interval,omitempty"`
	PacketSpec *PacketSpecApplyConfiguration `json:"packetSpec,omitempty"`
}

// TCPProbeApplyConfiguration constructs a declarative configuration of the TCPProbe type for use with
// apply.
func TCPProbe() *TCPProbeApplyConfiguration {
	return &TCPProbeApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *TCPProbeApplyConfiguration) WithHost(value string) *TCPProbeApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *TCPProbeApplyConfiguration) WithPort(value int32) *TCPProbeApplyConfiguration {
	b.Port = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *TCPProbeApplyConfiguration) WithInterval(value networkprobev1beta1.Duration) *TCPProbeApplyConfiguration {
	b.Interval = &value
	return b
}

// WithPacketSpec sets the PacketSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketSpec field is set to the value of the last call.
func (b *TCPProbeApplyConfiguration) WithPacketSpec(value *PacketSpecApplyConfiguration) *TCPProbeApplyConfiguration {
	b.PacketSpec = value
	return b
}
