/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// TLSConfigApplyConfiguration represents a declarative configuration of the TLSConfig type for use
// with apply.
type TLSConfigApplyConfiguration struct {
	CACert             *SecretOrConfigMapApplyConfiguration `json:"caCert,omitempty"`
	InsecureSkipVerify *bool                                `json:"insecureSkipVerify,omitempty"`
}

// TLSConfigApplyConfiguration constructs a declarative configuration of the TLSConfig type for use with
// apply.
func TLSConfig() *TLSConfigApplyConfiguration {
	return &TLSConfigApplyConfiguration{}
}

// WithCACert sets the CACert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CACert field is set to the value of the last call.
func (b *TLSConfigApplyConfiguration) WithCACert(value *SecretOrConfigMapApplyConfiguration) *TLSConfigApplyConfiguration {
	b.CACert = value
	return b
}

// WithInsecureSkipVerify sets the InsecureSkipVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureSkipVerify field is set to the value of the last call.
func (b *TLSConfigApplyConfiguration) WithInsecureSkipVerify(value bool) *TLSConfigApplyConfiguration {
	b.InsecureSkipVerify = &value
	return b
}
