/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
)

// UDPStreamProbeApplyConfiguration represents a declarative configuration of the UDPStreamProbe type for use
// with apply.
type UDPStreamProbeApplyConfiguration struct {
	Host           *string                       `json:"host,omitempty"`
	Port           *int32                        `json:"port,omitempty"`
	Interval       *v1beta1.Duration             `json:"interval,omitempty"`
	PacketCount    *int32                        `json:"packetCount,omitempty"`
	PacketInterval *v1beta1.Duration             `json:"packetInterval,omitempty"`
	PacketSpec     *PacketSpecApplyConfiguration `json:"packetSpec,omitempty"`
}

// UDPStreamProbeApplyConfiguration constructs a declarative configuration of the UDPStreamProbe type for use with
// apply.
func UDPStreamProbe() *UDPStreamProbeApplyConfiguration {
	return &UDPStreamProbeApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *UDPStreamProbeApplyConfiguration) WithHost(value string) *UDPStreamProbeApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *UDPStreamProbeApplyConfiguration) WithPort(value int32) *UDPStreamProbeApplyConfiguration {
	b.Port = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *UDPStreamProbeApplyConfiguration) WithInterval(value v1beta1.Duration) *UDPStreamProbeApplyConfiguration {
	b.Interval = &value
	return b
}

// WithPacketCount sets the PacketCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketCount field is set to the value of the last call.
func (b *UDPStreamProbeApplyConfiguration) WithPacketCount(value int32) *UDPStreamProbeApplyConfiguration {
	b.PacketCount = &value
	return b
}

// WithPacketInterval sets the PacketInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketInterval field is set to the value of the last call.
func (b *UDPStreamProbeApplyConfiguration) WithPacketInterval(value v1beta1.Duration) *UDPStreamProbeApplyConfiguration {
	b.PacketInterval = &value
	return b
}

// WithPacketSpec sets the PacketSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketSpec field is set to the value of the last call.
func (b *UDPStreamProbeApplyConfiguration) WithPacketSpec(value *PacketSpecApplyConfiguration) *UDPStreamProbeApplyConfiguration {
	b.PacketSpec = value
	return b
}
