// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	adminpbrv1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1"
	egressfirewallv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressfirewall/v1"
	apicorev1 "k8s.io/api/core/v1"
	corev1 "k8s.io/client-go/kubernetes/typed/core/v1"

	egressipv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	ipreservationv1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/ipreservation/v1beta1"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/openshift/api/cloudnetwork/v1"

	v1alpha1 "github.com/k8snetworkplumbingwg/ipamclaims/pkg/crd/ipamclaims/v1alpha1"

	v1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/portmirror/v1beta1"
)

// InterfaceOVN is an autogenerated mock type for the InterfaceOVN type
type InterfaceOVN struct {
	mock.Mock
}

// CreateCloudPrivateIPConfig provides a mock function with given fields: cloudPrivateIPConfig
func (_m *InterfaceOVN) CreateCloudPrivateIPConfig(cloudPrivateIPConfig *v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error) {
	ret := _m.Called(cloudPrivateIPConfig)

	if len(ret) == 0 {
		panic("no return value specified for CreateCloudPrivateIPConfig")
	}

	var r0 *v1.CloudPrivateIPConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error)); ok {
		return rf(cloudPrivateIPConfig)
	}
	if rf, ok := ret.Get(0).(func(*v1.CloudPrivateIPConfig) *v1.CloudPrivateIPConfig); ok {
		r0 = rf(cloudPrivateIPConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CloudPrivateIPConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.CloudPrivateIPConfig) error); ok {
		r1 = rf(cloudPrivateIPConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCloudPrivateIPConfig provides a mock function with given fields: name
func (_m *InterfaceOVN) DeleteCloudPrivateIPConfig(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCloudPrivateIPConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteConfigMap provides a mock function with given fields: namespace, name
func (_m *InterfaceOVN) DeleteConfigMap(namespace string, name string) error {
	ret := _m.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConfigMap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Events provides a mock function with no fields
func (_m *InterfaceOVN) Events() corev1.EventInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 corev1.EventInterface
	if rf, ok := ret.Get(0).(func() corev1.EventInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(corev1.EventInterface)
		}
	}

	return r0
}

// GetEgressFirewalls provides a mock function with no fields
func (_m *InterfaceOVN) GetEgressFirewalls() ([]*egressfirewallv1.EgressFirewall, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEgressFirewalls")
	}

	var r0 []*egressfirewallv1.EgressFirewall
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*egressfirewallv1.EgressFirewall, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*egressfirewallv1.EgressFirewall); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*egressfirewallv1.EgressFirewall)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEgressIP provides a mock function with given fields: name
func (_m *InterfaceOVN) GetEgressIP(name string) (*egressipv1.EgressIP, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetEgressIP")
	}

	var r0 *egressipv1.EgressIP
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*egressipv1.EgressIP, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *egressipv1.EgressIP); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*egressipv1.EgressIP)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEgressIPs provides a mock function with no fields
func (_m *InterfaceOVN) GetEgressIPs() ([]*egressipv1.EgressIP, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEgressIPs")
	}

	var r0 []*egressipv1.EgressIP
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*egressipv1.EgressIP, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*egressipv1.EgressIP); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*egressipv1.EgressIP)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodeForWindows provides a mock function with given fields: name
func (_m *InterfaceOVN) GetNodeForWindows(name string) (*apicorev1.Node, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeForWindows")
	}

	var r0 *apicorev1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*apicorev1.Node, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *apicorev1.Node); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apicorev1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodesForWindows provides a mock function with no fields
func (_m *InterfaceOVN) GetNodesForWindows() ([]*apicorev1.Node, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodesForWindows")
	}

	var r0 []*apicorev1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*apicorev1.Node, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*apicorev1.Node); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*apicorev1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPortMirror provides a mock function with given fields: namespace, name
func (_m *InterfaceOVN) GetPortMirror(namespace string, name string) (*v1beta1.PortMirror, error) {
	ret := _m.Called(namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPortMirror")
	}

	var r0 *v1beta1.PortMirror
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*v1beta1.PortMirror, error)); ok {
		return rf(namespace, name)
	}
	if rf, ok := ret.Get(0).(func(string, string) *v1beta1.PortMirror); ok {
		r0 = rf(namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1beta1.PortMirror)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchEgressIP provides a mock function with given fields: name, patchData
func (_m *InterfaceOVN) PatchEgressIP(name string, patchData []byte) error {
	ret := _m.Called(name, patchData)

	if len(ret) == 0 {
		panic("no return value specified for PatchEgressIP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(name, patchData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchNode provides a mock function with given fields: old, new
func (_m *InterfaceOVN) PatchNode(old *apicorev1.Node, new *apicorev1.Node) error {
	ret := _m.Called(old, new)

	if len(ret) == 0 {
		panic("no return value specified for PatchNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apicorev1.Node, *apicorev1.Node) error); ok {
		r0 = rf(old, new)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchPodStatusAnnotations provides a mock function with given fields: oldPod, newPod
func (_m *InterfaceOVN) PatchPodStatusAnnotations(oldPod *apicorev1.Pod, newPod *apicorev1.Pod) error {
	ret := _m.Called(oldPod, newPod)

	if len(ret) == 0 {
		panic("no return value specified for PatchPodStatusAnnotations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apicorev1.Pod, *apicorev1.Pod) error); ok {
		r0 = rf(oldPod, newPod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnNamespace provides a mock function with given fields: namespaceName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnNamespace(namespaceName string, annotations map[string]interface{}) error {
	ret := _m.Called(namespaceName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnNamespace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(namespaceName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnNode provides a mock function with given fields: nodeName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnNode(nodeName string, annotations map[string]interface{}) error {
	ret := _m.Called(nodeName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(nodeName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnNodeWithFieldManager provides a mock function with given fields: nodeName, annotations, fieldManager
func (_m *InterfaceOVN) SetAnnotationsOnNodeWithFieldManager(nodeName string, annotations map[string]interface{}, fieldManager string) error {
	ret := _m.Called(nodeName, annotations, fieldManager)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnNodeWithFieldManager")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}, string) error); ok {
		r0 = rf(nodeName, annotations, fieldManager)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnPod provides a mock function with given fields: namespace, podName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnPod(namespace string, podName string, annotations map[string]interface{}) error {
	ret := _m.Called(namespace, podName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnPod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]interface{}) error); ok {
		r0 = rf(namespace, podName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnService provides a mock function with given fields: namespace, serviceName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnService(namespace string, serviceName string, annotations map[string]interface{}) error {
	ret := _m.Called(namespace, serviceName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]interface{}) error); ok {
		r0 = rf(namespace, serviceName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLabelsOnNode provides a mock function with given fields: nodeName, labels
func (_m *InterfaceOVN) SetLabelsOnNode(nodeName string, labels map[string]interface{}) error {
	ret := _m.Called(nodeName, labels)

	if len(ret) == 0 {
		panic("no return value specified for SetLabelsOnNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(nodeName, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLabelsOnPod provides a mock function with given fields: pod, labels
func (_m *InterfaceOVN) SetLabelsOnPod(pod *apicorev1.Pod, labels map[string]string) error {
	ret := _m.Called(pod, labels)

	if len(ret) == 0 {
		panic("no return value specified for SetLabelsOnPod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apicorev1.Pod, map[string]string) error); ok {
		r0 = rf(pod, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAdminPBRStatus provides a mock function with given fields: adminpbr
func (_m *InterfaceOVN) UpdateAdminPBRStatus(adminpbr *adminpbrv1beta1.AdminPolicyBasedRoute) (*adminpbrv1beta1.AdminPolicyBasedRoute, error) {
	ret := _m.Called(adminpbr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAdminPBRStatus")
	}

	var r0 *adminpbrv1beta1.AdminPolicyBasedRoute
	var r1 error
	if rf, ok := ret.Get(0).(func(*adminpbrv1beta1.AdminPolicyBasedRoute) (*adminpbrv1beta1.AdminPolicyBasedRoute, error)); ok {
		return rf(adminpbr)
	}
	if rf, ok := ret.Get(0).(func(*adminpbrv1beta1.AdminPolicyBasedRoute) *adminpbrv1beta1.AdminPolicyBasedRoute); ok {
		r0 = rf(adminpbr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adminpbrv1beta1.AdminPolicyBasedRoute)
		}
	}

	if rf, ok := ret.Get(1).(func(*adminpbrv1beta1.AdminPolicyBasedRoute) error); ok {
		r1 = rf(adminpbr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCloudPrivateIPConfig provides a mock function with given fields: cloudPrivateIPConfig
func (_m *InterfaceOVN) UpdateCloudPrivateIPConfig(cloudPrivateIPConfig *v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error) {
	ret := _m.Called(cloudPrivateIPConfig)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCloudPrivateIPConfig")
	}

	var r0 *v1.CloudPrivateIPConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error)); ok {
		return rf(cloudPrivateIPConfig)
	}
	if rf, ok := ret.Get(0).(func(*v1.CloudPrivateIPConfig) *v1.CloudPrivateIPConfig); ok {
		r0 = rf(cloudPrivateIPConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CloudPrivateIPConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.CloudPrivateIPConfig) error); ok {
		r1 = rf(cloudPrivateIPConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEgressFirewall provides a mock function with given fields: egressfirewall
func (_m *InterfaceOVN) UpdateEgressFirewall(egressfirewall *egressfirewallv1.EgressFirewall) error {
	ret := _m.Called(egressfirewall)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEgressFirewall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*egressfirewallv1.EgressFirewall) error); ok {
		r0 = rf(egressfirewall)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEgressIP provides a mock function with given fields: eIP
func (_m *InterfaceOVN) UpdateEgressIP(eIP *egressipv1.EgressIP) error {
	ret := _m.Called(eIP)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEgressIP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*egressipv1.EgressIP) error); ok {
		r0 = rf(eIP)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEgressServiceStatus provides a mock function with given fields: namespace, name, host
func (_m *InterfaceOVN) UpdateEgressServiceStatus(namespace string, name string, host string) error {
	ret := _m.Called(namespace, name, host)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEgressServiceStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(namespace, name, host)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateIPAMClaimIPs provides a mock function with given fields: updatedIPAMClaim
func (_m *InterfaceOVN) UpdateIPAMClaimIPs(updatedIPAMClaim *v1alpha1.IPAMClaim) error {
	ret := _m.Called(updatedIPAMClaim)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIPAMClaimIPs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.IPAMClaim) error); ok {
		r0 = rf(updatedIPAMClaim)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateIPReservationStatus provides a mock function with given fields: status
func (_m *InterfaceOVN) UpdateIPReservationStatus(status *ipreservationv1beta1.IPReservation) error {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIPReservationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*ipreservationv1beta1.IPReservation) error); ok {
		r0 = rf(status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNodeStatus provides a mock function with given fields: node
func (_m *InterfaceOVN) UpdateNodeStatus(node *apicorev1.Node) error {
	ret := _m.Called(node)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNodeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apicorev1.Node) error); ok {
		r0 = rf(node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePortMirrorStatus provides a mock function with given fields: pm
func (_m *InterfaceOVN) UpdatePortMirrorStatus(pm *v1beta1.PortMirror) error {
	ret := _m.Called(pm)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePortMirrorStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1beta1.PortMirror) error); ok {
		r0 = rf(pm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInterfaceOVN creates a new instance of InterfaceOVN. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterfaceOVN(t interface {
	mock.TestingT
	Cleanup(func())
}) *InterfaceOVN {
	mock := &InterfaceOVN{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
