/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1"
	networkqosv1alpha1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1/apis/applyconfiguration/networkqos/v1alpha1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkqos/v1alpha1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetworkQoSesGetter has a method to return a NetworkQoSInterface.
// A group's client should implement this interface.
type NetworkQoSesGetter interface {
	NetworkQoSes(namespace string) NetworkQoSInterface
}

// NetworkQoSInterface has methods to work with NetworkQoS resources.
type NetworkQoSInterface interface {
	Create(ctx context.Context, networkQoS *v1alpha1.NetworkQoS, opts v1.CreateOptions) (*v1alpha1.NetworkQoS, error)
	Update(ctx context.Context, networkQoS *v1alpha1.NetworkQoS, opts v1.UpdateOptions) (*v1alpha1.NetworkQoS, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, networkQoS *v1alpha1.NetworkQoS, opts v1.UpdateOptions) (*v1alpha1.NetworkQoS, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NetworkQoS, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NetworkQoSList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkQoS, err error)
	Apply(ctx context.Context, networkQoS *networkqosv1alpha1.NetworkQoSApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkQoS, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, networkQoS *networkqosv1alpha1.NetworkQoSApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkQoS, err error)
	NetworkQoSExpansion
}

// networkQoSes implements NetworkQoSInterface
type networkQoSes struct {
	*gentype.ClientWithListAndApply[*v1alpha1.NetworkQoS, *v1alpha1.NetworkQoSList, *networkqosv1alpha1.NetworkQoSApplyConfiguration]
}

// newNetworkQoSes returns a NetworkQoSes
func newNetworkQoSes(c *K8sV1alpha1Client, namespace string) *networkQoSes {
	return &networkQoSes{
		gentype.NewClientWithListAndApply[*v1alpha1.NetworkQoS, *v1alpha1.NetworkQoSList, *networkqosv1alpha1.NetworkQoSApplyConfiguration](
			"networkqoses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.NetworkQoS { return &v1alpha1.NetworkQoS{} },
			func() *v1alpha1.NetworkQoSList { return &v1alpha1.NetworkQoSList{} }),
	}
}
