//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSProbe) DeepCopyInto(out *DNSProbe) {
	*out = *in
	out.PacketSpec = in.PacketSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSProbe.
func (in *DNSProbe) DeepCopy() *DNSProbe {
	if in == nil {
		return nil
	}
	out := new(DNSProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProbe) DeepCopyInto(out *HTTPProbe) {
	*out = *in
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	out.PacketSpec = in.PacketSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProbe.
func (in *HTTPProbe) DeepCopy() *HTTPProbe {
	if in == nil {
		return nil
	}
	out := new(HTTPProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProbe) DeepCopyInto(out *NetworkProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProbe.
func (in *NetworkProbe) DeepCopy() *NetworkProbe {
	if in == nil {
		return nil
	}
	out := new(NetworkProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProbeList) DeepCopyInto(out *NetworkProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProbeList.
func (in *NetworkProbeList) DeepCopy() *NetworkProbeList {
	if in == nil {
		return nil
	}
	out := new(NetworkProbeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProbeSpec) DeepCopyInto(out *NetworkProbeSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.DNSProbes != nil {
		in, out := &in.DNSProbes, &out.DNSProbes
		*out = make([]DNSProbe, len(*in))
		copy(*out, *in)
	}
	if in.HTTPProbes != nil {
		in, out := &in.HTTPProbes, &out.HTTPProbes
		*out = make([]HTTPProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TCPProbes != nil {
		in, out := &in.TCPProbes, &out.TCPProbes
		*out = make([]TCPProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UDPStreamProbes != nil {
		in, out := &in.UDPStreamProbes, &out.UDPStreamProbes
		*out = make([]UDPStreamProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProbeSpec.
func (in *NetworkProbeSpec) DeepCopy() *NetworkProbeSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProbeStatus) DeepCopyInto(out *NetworkProbeStatus) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProbeStatus.
func (in *NetworkProbeStatus) DeepCopy() *NetworkProbeStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacketSpec) DeepCopyInto(out *PacketSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacketSpec.
func (in *PacketSpec) DeepCopy() *PacketSpec {
	if in == nil {
		return nil
	}
	out := new(PacketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPProbe) DeepCopyInto(out *TCPProbe) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	out.PacketSpec = in.PacketSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPProbe.
func (in *TCPProbe) DeepCopy() *TCPProbe {
	if in == nil {
		return nil
	}
	out := new(TCPProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CAConfigMap != nil {
		in, out := &in.CAConfigMap, &out.CAConfigMap
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDPStreamProbe) DeepCopyInto(out *UDPStreamProbe) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.PacketCount != nil {
		in, out := &in.PacketCount, &out.PacketCount
		*out = new(int32)
		**out = **in
	}
	out.PacketSpec = in.PacketSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDPStreamProbe.
func (in *UDPStreamProbe) DeepCopy() *UDPStreamProbe {
	if in == nil {
		return nil
	}
	out := new(UDPStreamProbe)
	in.DeepCopyInto(out)
	return out
}
