/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ipreservation/v1beta1"
	ipreservationv1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ipreservation/v1beta1/apis/applyconfiguration/ipreservation/v1beta1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ipreservation/v1beta1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPReservationsGetter has a method to return a IPReservationInterface.
// A group's client should implement this interface.
type IPReservationsGetter interface {
	IPReservations(namespace string) IPReservationInterface
}

// IPReservationInterface has methods to work with IPReservation resources.
type IPReservationInterface interface {
	Create(ctx context.Context, iPReservation *v1beta1.IPReservation, opts v1.CreateOptions) (*v1beta1.IPReservation, error)
	Update(ctx context.Context, iPReservation *v1beta1.IPReservation, opts v1.UpdateOptions) (*v1beta1.IPReservation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPReservation *v1beta1.IPReservation, opts v1.UpdateOptions) (*v1beta1.IPReservation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.IPReservation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.IPReservationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.IPReservation, err error)
	Apply(ctx context.Context, iPReservation *ipreservationv1beta1.IPReservationApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.IPReservation, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, iPReservation *ipreservationv1beta1.IPReservationApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.IPReservation, err error)
	IPReservationExpansion
}

// iPReservations implements IPReservationInterface
type iPReservations struct {
	*gentype.ClientWithListAndApply[*v1beta1.IPReservation, *v1beta1.IPReservationList, *ipreservationv1beta1.IPReservationApplyConfiguration]
}

// newIPReservations returns a IPReservations
func newIPReservations(c *K8sV1beta1Client, namespace string) *iPReservations {
	return &iPReservations{
		gentype.NewClientWithListAndApply[*v1beta1.IPReservation, *v1beta1.IPReservationList, *ipreservationv1beta1.IPReservationApplyConfiguration](
			"ipreservations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.IPReservation { return &v1beta1.IPReservation{} },
			func() *v1beta1.IPReservationList { return &v1beta1.IPReservationList{} }),
	}
}
