
stages:
  - make-and-check

include:
  - cicd/runners-tags.yml

.always:
  rules:
    - when: always

make-build:amd64:
  stage: make-and-check
  image: ${image}
  extends:
    - .tags-amd64
    - .always
  script:
    - make build -C go-controller

make-windows:amd64:
  stage: make-and-check
  image: ${image}
  extends:
    - .tags-amd64
    - .always
  script:
    - make windows -C go-controller

make-gofmt:amd64:
  stage: make-and-check
  image: ${image}
  extends:
    - .tags-amd64
    - .always
  script:
    - make gofmt -C go-controller

make-check:amd64:
  stage: make-and-check
  image: ${image}
  extends:
    - .tags-amd64
    - .always
  parallel: 11
  script:
    - pushd go-controller && go list -buildvcs=false -mod vendor -f '{{if len .TestGoFiles}} {{.Dir}} {{end}}' ./cmd/... ./pkg/... ./hybrid-overlay/... | sort > ../.all-packages.txt && popd
    - split -d -n l/$CI_NODE_TOTAL ./.all-packages.txt pkgs_
    - FILE_INDEX=$(printf "%02d" $((CI_NODE_INDEX - 1)))
    - cat pkgs_${FILE_INDEX}
    - make check -C go-controller CGO_ENABLED=1 PKGS="$(cat pkgs_${FILE_INDEX} | xargs)"



