// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// MirrorSinkDeviceApplyConfiguration represents a declarative configuration of the MirrorSinkDevice type for use
// with apply.
type MirrorSinkDeviceApplyConfiguration struct {
	DeviceType *string `json:"deviceType,omitempty"`
	SFNum      *int    `json:"sfNum,omitempty"`
}

// MirrorSinkDeviceApplyConfiguration constructs a declarative configuration of the MirrorSinkDevice type for use with
// apply.
func MirrorSinkDevice() *MirrorSinkDeviceApplyConfiguration {
	return &MirrorSinkDeviceApplyConfiguration{}
}

// WithDeviceType sets the DeviceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceType field is set to the value of the last call.
func (b *MirrorSinkDeviceApplyConfiguration) WithDeviceType(value string) *MirrorSinkDeviceApplyConfiguration {
	b.DeviceType = &value
	return b
}

// WithSFNum sets the SFNum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SFNum field is set to the value of the last call.
func (b *MirrorSinkDeviceApplyConfiguration) WithSFNum(value int) *MirrorSinkDeviceApplyConfiguration {
	b.SFNum = &value
	return b
}
