// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PortMirrorSinkLocalApplyConfiguration represents a declarative configuration of the PortMirrorSinkLocal type for use
// with apply.
type PortMirrorSinkLocalApplyConfiguration struct {
	PodSelector *v1.LabelSelectorApplyConfiguration `json:"podSelector,omitempty"`
	NetDevName  *string                             `json:"netDevName,omitempty"`
	MirrorID    *string                             `json:"mirrorID,omitempty"`
	DeviceInfo  *MirrorSinkDeviceApplyConfiguration `json:"deviceInfo,omitempty"`
}

// PortMirrorSinkLocalApplyConfiguration constructs a declarative configuration of the PortMirrorSinkLocal type for use with
// apply.
func PortMirrorSinkLocal() *PortMirrorSinkLocalApplyConfiguration {
	return &PortMirrorSinkLocalApplyConfiguration{}
}

// WithPodSelector sets the PodSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSelector field is set to the value of the last call.
func (b *PortMirrorSinkLocalApplyConfiguration) WithPodSelector(value *v1.LabelSelectorApplyConfiguration) *PortMirrorSinkLocalApplyConfiguration {
	b.PodSelector = value
	return b
}

// WithNetDevName sets the NetDevName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetDevName field is set to the value of the last call.
func (b *PortMirrorSinkLocalApplyConfiguration) WithNetDevName(value string) *PortMirrorSinkLocalApplyConfiguration {
	b.NetDevName = &value
	return b
}

// WithMirrorID sets the MirrorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MirrorID field is set to the value of the last call.
func (b *PortMirrorSinkLocalApplyConfiguration) WithMirrorID(value string) *PortMirrorSinkLocalApplyConfiguration {
	b.MirrorID = &value
	return b
}

// WithDeviceInfo sets the DeviceInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceInfo field is set to the value of the last call.
func (b *PortMirrorSinkLocalApplyConfiguration) WithDeviceInfo(value *MirrorSinkDeviceApplyConfiguration) *PortMirrorSinkLocalApplyConfiguration {
	b.DeviceInfo = value
	return b
}
