#
# This is just bridging pipeline between
# ovn-kubernetes pipelines and sdn/sdn-helm/ovn-kubernetes pipeline.
# Purpose of it is variables isolation (see details in .gitlab-ci.yml)
#
stages:
  - downstream

.always:
  rules:
    - when: always

promote-helm:trigger:
  stage: downstream
  extends:
    - .always
  trigger:
    project: $helm_repo
    branch: $helm_branch
    strategy: depend
    forward:
      yaml_variables: true
