/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	portmirrorv1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/portmirror/v1beta1"
	applyconfigurationportmirrorv1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/portmirror/v1beta1/apis/applyconfiguration/portmirror/v1beta1"
	scheme "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/portmirror/v1beta1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PortMirrorsGetter has a method to return a PortMirrorInterface.
// A group's client should implement this interface.
type PortMirrorsGetter interface {
	PortMirrors(namespace string) PortMirrorInterface
}

// PortMirrorInterface has methods to work with PortMirror resources.
type PortMirrorInterface interface {
	Create(ctx context.Context, portMirror *portmirrorv1beta1.PortMirror, opts v1.CreateOptions) (*portmirrorv1beta1.PortMirror, error)
	Update(ctx context.Context, portMirror *portmirrorv1beta1.PortMirror, opts v1.UpdateOptions) (*portmirrorv1beta1.PortMirror, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, portMirror *portmirrorv1beta1.PortMirror, opts v1.UpdateOptions) (*portmirrorv1beta1.PortMirror, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*portmirrorv1beta1.PortMirror, error)
	List(ctx context.Context, opts v1.ListOptions) (*portmirrorv1beta1.PortMirrorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *portmirrorv1beta1.PortMirror, err error)
	Apply(ctx context.Context, portMirror *applyconfigurationportmirrorv1beta1.PortMirrorApplyConfiguration, opts v1.ApplyOptions) (result *portmirrorv1beta1.PortMirror, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, portMirror *applyconfigurationportmirrorv1beta1.PortMirrorApplyConfiguration, opts v1.ApplyOptions) (result *portmirrorv1beta1.PortMirror, err error)
	PortMirrorExpansion
}

// portMirrors implements PortMirrorInterface
type portMirrors struct {
	*gentype.ClientWithListAndApply[*portmirrorv1beta1.PortMirror, *portmirrorv1beta1.PortMirrorList, *applyconfigurationportmirrorv1beta1.PortMirrorApplyConfiguration]
}

// newPortMirrors returns a PortMirrors
func newPortMirrors(c *K8sV1beta1Client, namespace string) *portMirrors {
	return &portMirrors{
		gentype.NewClientWithListAndApply[*portmirrorv1beta1.PortMirror, *portmirrorv1beta1.PortMirrorList, *applyconfigurationportmirrorv1beta1.PortMirrorApplyConfiguration](
			"portmirrors",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *portmirrorv1beta1.PortMirror { return &portmirrorv1beta1.PortMirror{} },
			func() *portmirrorv1beta1.PortMirrorList { return &portmirrorv1beta1.PortMirrorList{} },
		),
	}
}
