/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ipreservation/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// IPReservationLister helps list IPReservations.
// All objects returned here must be treated as read-only.
type IPReservationLister interface {
	// List lists all IPReservations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.IPReservation, err error)
	// IPReservations returns an object that can list and get IPReservations.
	IPReservations(namespace string) IPReservationNamespaceLister
	IPReservationListerExpansion
}

// iPReservationLister implements the IPReservationLister interface.
type iPReservationLister struct {
	listers.ResourceIndexer[*v1beta1.IPReservation]
}

// NewIPReservationLister returns a new IPReservationLister.
func NewIPReservationLister(indexer cache.Indexer) IPReservationLister {
	return &iPReservationLister{listers.New[*v1beta1.IPReservation](indexer, v1beta1.Resource("ipreservation"))}
}

// IPReservations returns an object that can list and get IPReservations.
func (s *iPReservationLister) IPReservations(namespace string) IPReservationNamespaceLister {
	return iPReservationNamespaceLister{listers.NewNamespaced[*v1beta1.IPReservation](s.ResourceIndexer, namespace)}
}

// IPReservationNamespaceLister helps list and get IPReservations.
// All objects returned here must be treated as read-only.
type IPReservationNamespaceLister interface {
	// List lists all IPReservations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.IPReservation, err error)
	// Get retrieves the IPReservation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.IPReservation, error)
	IPReservationNamespaceListerExpansion
}

// iPReservationNamespaceLister implements the IPReservationNamespaceLister
// interface.
type iPReservationNamespaceLister struct {
	listers.ResourceIndexer[*v1beta1.IPReservation]
}
