/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/portmirror/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// PortMirrorLister helps list PortMirrors.
// All objects returned here must be treated as read-only.
type PortMirrorLister interface {
	// List lists all PortMirrors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.PortMirror, err error)
	// PortMirrors returns an object that can list and get PortMirrors.
	PortMirrors(namespace string) PortMirrorNamespaceLister
	PortMirrorListerExpansion
}

// portMirrorLister implements the PortMirrorLister interface.
type portMirrorLister struct {
	listers.ResourceIndexer[*v1beta1.PortMirror]
}

// NewPortMirrorLister returns a new PortMirrorLister.
func NewPortMirrorLister(indexer cache.Indexer) PortMirrorLister {
	return &portMirrorLister{listers.New[*v1beta1.PortMirror](indexer, v1beta1.Resource("portmirror"))}
}

// PortMirrors returns an object that can list and get PortMirrors.
func (s *portMirrorLister) PortMirrors(namespace string) PortMirrorNamespaceLister {
	return portMirrorNamespaceLister{listers.NewNamespaced[*v1beta1.PortMirror](s.ResourceIndexer, namespace)}
}

// PortMirrorNamespaceLister helps list and get PortMirrors.
// All objects returned here must be treated as read-only.
type PortMirrorNamespaceLister interface {
	// List lists all PortMirrors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.PortMirror, err error)
	// Get retrieves the PortMirror from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.PortMirror, error)
	PortMirrorNamespaceListerExpansion
}

// portMirrorNamespaceLister implements the PortMirrorNamespaceLister
// interface.
type portMirrorNamespaceLister struct {
	listers.ResourceIndexer[*v1beta1.PortMirror]
}
