/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkProbes implements NetworkProbeInterface
type FakeNetworkProbes struct {
	Fake *FakeK8sV1beta1
	ns   string
}

var networkprobesResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1beta1", Resource: "networkprobes"}

var networkprobesKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1beta1", Kind: "NetworkProbe"}

// Get takes name of the networkProbe, and returns the corresponding networkProbe object, and an error if there is any.
func (c *FakeNetworkProbes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetworkProbe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkprobesResource, c.ns, name), &v1beta1.NetworkProbe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkProbe), err
}

// List takes label and field selectors, and returns the list of NetworkProbes that match those selectors.
func (c *FakeNetworkProbes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetworkProbeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkprobesResource, networkprobesKind, c.ns, opts), &v1beta1.NetworkProbeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NetworkProbeList{ListMeta: obj.(*v1beta1.NetworkProbeList).ListMeta}
	for _, item := range obj.(*v1beta1.NetworkProbeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkProbes.
func (c *FakeNetworkProbes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkprobesResource, c.ns, opts))

}

// Create takes the representation of a networkProbe and creates it.  Returns the server's representation of the networkProbe, and an error, if there is any.
func (c *FakeNetworkProbes) Create(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.CreateOptions) (result *v1beta1.NetworkProbe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkprobesResource, c.ns, networkProbe), &v1beta1.NetworkProbe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkProbe), err
}

// Update takes the representation of a networkProbe and updates it. Returns the server's representation of the networkProbe, and an error, if there is any.
func (c *FakeNetworkProbes) Update(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.UpdateOptions) (result *v1beta1.NetworkProbe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkprobesResource, c.ns, networkProbe), &v1beta1.NetworkProbe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkProbe), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkProbes) UpdateStatus(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.UpdateOptions) (*v1beta1.NetworkProbe, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(networkprobesResource, "status", c.ns, networkProbe), &v1beta1.NetworkProbe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkProbe), err
}

// Delete takes name of the networkProbe and deletes it. Returns an error if one occurs.
func (c *FakeNetworkProbes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networkprobesResource, c.ns, name), &v1beta1.NetworkProbe{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkProbes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkprobesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NetworkProbeList{})
	return err
}

// Patch applies the patch and returns the patched networkProbe.
func (c *FakeNetworkProbes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetworkProbe, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkprobesResource, c.ns, name, pt, data, subresources...), &v1beta1.NetworkProbe{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NetworkProbe), err
}
