// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AdminPolicyBasedRouteSpecApplyConfiguration represents a declarative configuration of the AdminPolicyBasedRouteSpec type for use
// with apply.
type AdminPolicyBasedRouteSpecApplyConfiguration struct {
	NetworkAttachmentName *string                               `json:"networkAttachmentName,omitempty"`
	Policies              []RoutingPolicyRuleApplyConfiguration `json:"policies,omitempty"`
}

// AdminPolicyBasedRouteSpecApplyConfiguration constructs a declarative configuration of the AdminPolicyBasedRouteSpec type for use with
// apply.
func AdminPolicyBasedRouteSpec() *AdminPolicyBasedRouteSpecApplyConfiguration {
	return &AdminPolicyBasedRouteSpecApplyConfiguration{}
}

// WithNetworkAttachmentName sets the NetworkAttachmentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkAttachmentName field is set to the value of the last call.
func (b *AdminPolicyBasedRouteSpecApplyConfiguration) WithNetworkAttachmentName(value string) *AdminPolicyBasedRouteSpecApplyConfiguration {
	b.NetworkAttachmentName = &value
	return b
}

// WithPolicies adds the given value to the Policies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Policies field.
func (b *AdminPolicyBasedRouteSpecApplyConfiguration) WithPolicies(values ...*RoutingPolicyRuleApplyConfiguration) *AdminPolicyBasedRouteSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPolicies")
		}
		b.Policies = append(b.Policies, *values[i])
	}
	return b
}
