/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/networking/v1"
)

// RoutingPolicyRuleApplyConfiguration represents a declarative configuration of the RoutingPolicyRule type for use
// with apply.
type RoutingPolicyRuleApplyConfiguration struct {
	From    *RoutingPolicyMatchApplyConfiguration   `json:"from,omitempty"`
	To      *v1.IPBlock                             `json:"to,omitempty"`
	NextHop *RoutingPolicyNextHopApplyConfiguration `json:"nexthop,omitempty"`
}

// RoutingPolicyRuleApplyConfiguration constructs a declarative configuration of the RoutingPolicyRule type for use with
// apply.
func RoutingPolicyRule() *RoutingPolicyRuleApplyConfiguration {
	return &RoutingPolicyRuleApplyConfiguration{}
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *RoutingPolicyRuleApplyConfiguration) WithFrom(value *RoutingPolicyMatchApplyConfiguration) *RoutingPolicyRuleApplyConfiguration {
	b.From = value
	return b
}

// WithTo sets the To field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the To field is set to the value of the last call.
func (b *RoutingPolicyRuleApplyConfiguration) WithTo(value v1.IPBlock) *RoutingPolicyRuleApplyConfiguration {
	b.To = &value
	return b
}

// WithNextHop sets the NextHop field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NextHop field is set to the value of the last call.
func (b *RoutingPolicyRuleApplyConfiguration) WithNextHop(value *RoutingPolicyNextHopApplyConfiguration) *RoutingPolicyRuleApplyConfiguration {
	b.NextHop = value
	return b
}
