// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// RoutingPolicyNextHopApplyConfiguration represents a declarative configuration of the RoutingPolicyNextHop type for use
// with apply.
type RoutingPolicyNextHopApplyConfiguration struct {
	NextHopIPs []string `json:"ips,omitempty"`
}

// RoutingPolicyNextHopApplyConfiguration constructs a declarative configuration of the RoutingPolicyNextHop type for use with
// apply.
func RoutingPolicyNextHop() *RoutingPolicyNextHopApplyConfiguration {
	return &RoutingPolicyNextHopApplyConfiguration{}
}

// WithNextHopIPs adds the given value to the NextHopIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NextHopIPs field.
func (b *RoutingPolicyNextHopApplyConfiguration) WithNextHopIPs(values ...string) *RoutingPolicyNextHopApplyConfiguration {
	for i := range values {
		b.NextHopIPs = append(b.NextHopIPs, values[i])
	}
	return b
}
