// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	adminpbrv1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1"
	applyconfigurationadminpbrv1beta1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1/apis/applyconfiguration/adminpbr/v1beta1"
	scheme "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AdminPolicyBasedRoutesGetter has a method to return a AdminPolicyBasedRouteInterface.
// A group's client should implement this interface.
type AdminPolicyBasedRoutesGetter interface {
	AdminPolicyBasedRoutes() AdminPolicyBasedRouteInterface
}

// AdminPolicyBasedRouteInterface has methods to work with AdminPolicyBasedRoute resources.
type AdminPolicyBasedRouteInterface interface {
	Create(ctx context.Context, adminPolicyBasedRoute *adminpbrv1beta1.AdminPolicyBasedRoute, opts v1.CreateOptions) (*adminpbrv1beta1.AdminPolicyBasedRoute, error)
	Update(ctx context.Context, adminPolicyBasedRoute *adminpbrv1beta1.AdminPolicyBasedRoute, opts v1.UpdateOptions) (*adminpbrv1beta1.AdminPolicyBasedRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, adminPolicyBasedRoute *adminpbrv1beta1.AdminPolicyBasedRoute, opts v1.UpdateOptions) (*adminpbrv1beta1.AdminPolicyBasedRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*adminpbrv1beta1.AdminPolicyBasedRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*adminpbrv1beta1.AdminPolicyBasedRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *adminpbrv1beta1.AdminPolicyBasedRoute, err error)
	Apply(ctx context.Context, adminPolicyBasedRoute *applyconfigurationadminpbrv1beta1.AdminPolicyBasedRouteApplyConfiguration, opts v1.ApplyOptions) (result *adminpbrv1beta1.AdminPolicyBasedRoute, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, adminPolicyBasedRoute *applyconfigurationadminpbrv1beta1.AdminPolicyBasedRouteApplyConfiguration, opts v1.ApplyOptions) (result *adminpbrv1beta1.AdminPolicyBasedRoute, err error)
	AdminPolicyBasedRouteExpansion
}

// adminPolicyBasedRoutes implements AdminPolicyBasedRouteInterface
type adminPolicyBasedRoutes struct {
	*gentype.ClientWithListAndApply[*adminpbrv1beta1.AdminPolicyBasedRoute, *adminpbrv1beta1.AdminPolicyBasedRouteList, *applyconfigurationadminpbrv1beta1.AdminPolicyBasedRouteApplyConfiguration]
}

// newAdminPolicyBasedRoutes returns a AdminPolicyBasedRoutes
func newAdminPolicyBasedRoutes(c *K8sV1beta1Client) *adminPolicyBasedRoutes {
	return &adminPolicyBasedRoutes{
		gentype.NewClientWithListAndApply[*adminpbrv1beta1.AdminPolicyBasedRoute, *adminpbrv1beta1.AdminPolicyBasedRouteList, *applyconfigurationadminpbrv1beta1.AdminPolicyBasedRouteApplyConfiguration](
			"adminpolicybasedroutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *adminpbrv1beta1.AdminPolicyBasedRoute { return &adminpbrv1beta1.AdminPolicyBasedRoute{} },
			func() *adminpbrv1beta1.AdminPolicyBasedRouteList { return &adminpbrv1beta1.AdminPolicyBasedRouteList{} },
		),
	}
}
