/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/adminpbr/v1beta1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AdminPolicyBasedRoutesGetter has a method to return a AdminPolicyBasedRouteInterface.
// A group's client should implement this interface.
type AdminPolicyBasedRoutesGetter interface {
	AdminPolicyBasedRoutes() AdminPolicyBasedRouteInterface
}

// AdminPolicyBasedRouteInterface has methods to work with AdminPolicyBasedRoute resources.
type AdminPolicyBasedRouteInterface interface {
	Create(ctx context.Context, adminPolicyBasedRoute *v1beta1.AdminPolicyBasedRoute, opts v1.CreateOptions) (*v1beta1.AdminPolicyBasedRoute, error)
	Update(ctx context.Context, adminPolicyBasedRoute *v1beta1.AdminPolicyBasedRoute, opts v1.UpdateOptions) (*v1beta1.AdminPolicyBasedRoute, error)
	UpdateStatus(ctx context.Context, adminPolicyBasedRoute *v1beta1.AdminPolicyBasedRoute, opts v1.UpdateOptions) (*v1beta1.AdminPolicyBasedRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.AdminPolicyBasedRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.AdminPolicyBasedRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AdminPolicyBasedRoute, err error)
	AdminPolicyBasedRouteExpansion
}

// adminPolicyBasedRoutes implements AdminPolicyBasedRouteInterface
type adminPolicyBasedRoutes struct {
	client rest.Interface
}

// newAdminPolicyBasedRoutes returns a AdminPolicyBasedRoutes
func newAdminPolicyBasedRoutes(c *K8sV1beta1Client) *adminPolicyBasedRoutes {
	return &adminPolicyBasedRoutes{
		client: c.RESTClient(),
	}
}

// Get takes name of the adminPolicyBasedRoute, and returns the corresponding adminPolicyBasedRoute object, and an error if there is any.
func (c *adminPolicyBasedRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.AdminPolicyBasedRoute, err error) {
	result = &v1beta1.AdminPolicyBasedRoute{}
	err = c.client.Get().
		Resource("adminpolicybasedroutes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AdminPolicyBasedRoutes that match those selectors.
func (c *adminPolicyBasedRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.AdminPolicyBasedRouteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.AdminPolicyBasedRouteList{}
	err = c.client.Get().
		Resource("adminpolicybasedroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested adminPolicyBasedRoutes.
func (c *adminPolicyBasedRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("adminpolicybasedroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a adminPolicyBasedRoute and creates it.  Returns the server's representation of the adminPolicyBasedRoute, and an error, if there is any.
func (c *adminPolicyBasedRoutes) Create(ctx context.Context, adminPolicyBasedRoute *v1beta1.AdminPolicyBasedRoute, opts v1.CreateOptions) (result *v1beta1.AdminPolicyBasedRoute, err error) {
	result = &v1beta1.AdminPolicyBasedRoute{}
	err = c.client.Post().
		Resource("adminpolicybasedroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(adminPolicyBasedRoute).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a adminPolicyBasedRoute and updates it. Returns the server's representation of the adminPolicyBasedRoute, and an error, if there is any.
func (c *adminPolicyBasedRoutes) Update(ctx context.Context, adminPolicyBasedRoute *v1beta1.AdminPolicyBasedRoute, opts v1.UpdateOptions) (result *v1beta1.AdminPolicyBasedRoute, err error) {
	result = &v1beta1.AdminPolicyBasedRoute{}
	err = c.client.Put().
		Resource("adminpolicybasedroutes").
		Name(adminPolicyBasedRoute.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(adminPolicyBasedRoute).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *adminPolicyBasedRoutes) UpdateStatus(ctx context.Context, adminPolicyBasedRoute *v1beta1.AdminPolicyBasedRoute, opts v1.UpdateOptions) (result *v1beta1.AdminPolicyBasedRoute, err error) {
	result = &v1beta1.AdminPolicyBasedRoute{}
	err = c.client.Put().
		Resource("adminpolicybasedroutes").
		Name(adminPolicyBasedRoute.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(adminPolicyBasedRoute).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the adminPolicyBasedRoute and deletes it. Returns an error if one occurs.
func (c *adminPolicyBasedRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("adminpolicybasedroutes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *adminPolicyBasedRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("adminpolicybasedroutes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched adminPolicyBasedRoute.
func (c *adminPolicyBasedRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.AdminPolicyBasedRoute, err error) {
	result = &v1beta1.AdminPolicyBasedRoute{}
	err = c.client.Patch(pt).
		Resource("adminpolicybasedroutes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
