/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualip/v1beta1"
	virtualipv1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualip/v1beta1/apis/applyconfiguration/virtualip/v1beta1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualip/v1beta1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VirtualIPsGetter has a method to return a VirtualIPInterface.
// A group's client should implement this interface.
type VirtualIPsGetter interface {
	VirtualIPs(namespace string) VirtualIPInterface
}

// VirtualIPInterface has methods to work with VirtualIP resources.
type VirtualIPInterface interface {
	Create(ctx context.Context, virtualIP *v1beta1.VirtualIP, opts v1.CreateOptions) (*v1beta1.VirtualIP, error)
	Update(ctx context.Context, virtualIP *v1beta1.VirtualIP, opts v1.UpdateOptions) (*v1beta1.VirtualIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualIP *v1beta1.VirtualIP, opts v1.UpdateOptions) (*v1beta1.VirtualIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.VirtualIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.VirtualIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VirtualIP, err error)
	Apply(ctx context.Context, virtualIP *virtualipv1beta1.VirtualIPApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.VirtualIP, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, virtualIP *virtualipv1beta1.VirtualIPApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.VirtualIP, err error)
	VirtualIPExpansion
}

// virtualIPs implements VirtualIPInterface
type virtualIPs struct {
	*gentype.ClientWithListAndApply[*v1beta1.VirtualIP, *v1beta1.VirtualIPList, *virtualipv1beta1.VirtualIPApplyConfiguration]
}

// newVirtualIPs returns a VirtualIPs
func newVirtualIPs(c *K8sV1beta1Client, namespace string) *virtualIPs {
	return &virtualIPs{
		gentype.NewClientWithListAndApply[*v1beta1.VirtualIP, *v1beta1.VirtualIPList, *virtualipv1beta1.VirtualIPApplyConfiguration](
			"virtualips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.VirtualIP { return &v1beta1.VirtualIP{} },
			func() *v1beta1.VirtualIPList { return &v1beta1.VirtualIPList{} }),
	}
}
