/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkProbesGetter has a method to return a NetworkProbeInterface.
// A group's client should implement this interface.
type NetworkProbesGetter interface {
	NetworkProbes(namespace string) NetworkProbeInterface
}

// NetworkProbeInterface has methods to work with NetworkProbe resources.
type NetworkProbeInterface interface {
	Create(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.CreateOptions) (*v1beta1.NetworkProbe, error)
	Update(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.UpdateOptions) (*v1beta1.NetworkProbe, error)
	UpdateStatus(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.UpdateOptions) (*v1beta1.NetworkProbe, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.NetworkProbe, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.NetworkProbeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetworkProbe, err error)
	NetworkProbeExpansion
}

// networkProbes implements NetworkProbeInterface
type networkProbes struct {
	client rest.Interface
	ns     string
}

// newNetworkProbes returns a NetworkProbes
func newNetworkProbes(c *K8sV1beta1Client, namespace string) *networkProbes {
	return &networkProbes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the networkProbe, and returns the corresponding networkProbe object, and an error if there is any.
func (c *networkProbes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NetworkProbe, err error) {
	result = &v1beta1.NetworkProbe{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkprobes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkProbes that match those selectors.
func (c *networkProbes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NetworkProbeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.NetworkProbeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkprobes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkProbes.
func (c *networkProbes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("networkprobes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkProbe and creates it.  Returns the server's representation of the networkProbe, and an error, if there is any.
func (c *networkProbes) Create(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.CreateOptions) (result *v1beta1.NetworkProbe, err error) {
	result = &v1beta1.NetworkProbe{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("networkprobes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkProbe).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkProbe and updates it. Returns the server's representation of the networkProbe, and an error, if there is any.
func (c *networkProbes) Update(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.UpdateOptions) (result *v1beta1.NetworkProbe, err error) {
	result = &v1beta1.NetworkProbe{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkprobes").
		Name(networkProbe.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkProbe).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *networkProbes) UpdateStatus(ctx context.Context, networkProbe *v1beta1.NetworkProbe, opts v1.UpdateOptions) (result *v1beta1.NetworkProbe, err error) {
	result = &v1beta1.NetworkProbe{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkprobes").
		Name(networkProbe.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkProbe).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkProbe and deletes it. Returns an error if one occurs.
func (c *networkProbes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkprobes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkProbes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkprobes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkProbe.
func (c *networkProbes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NetworkProbe, err error) {
	result = &v1beta1.NetworkProbe{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("networkprobes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
