/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	networkprobev1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
	applyconfigurationnetworkprobev1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1/apis/applyconfiguration/networkprobe/v1beta1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetworkProbesGetter has a method to return a NetworkProbeInterface.
// A group's client should implement this interface.
type NetworkProbesGetter interface {
	NetworkProbes(namespace string) NetworkProbeInterface
}

// NetworkProbeInterface has methods to work with NetworkProbe resources.
type NetworkProbeInterface interface {
	Create(ctx context.Context, networkProbe *networkprobev1beta1.NetworkProbe, opts v1.CreateOptions) (*networkprobev1beta1.NetworkProbe, error)
	Update(ctx context.Context, networkProbe *networkprobev1beta1.NetworkProbe, opts v1.UpdateOptions) (*networkprobev1beta1.NetworkProbe, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, networkProbe *networkprobev1beta1.NetworkProbe, opts v1.UpdateOptions) (*networkprobev1beta1.NetworkProbe, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkprobev1beta1.NetworkProbe, error)
	List(ctx context.Context, opts v1.ListOptions) (*networkprobev1beta1.NetworkProbeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkprobev1beta1.NetworkProbe, err error)
	Apply(ctx context.Context, networkProbe *applyconfigurationnetworkprobev1beta1.NetworkProbeApplyConfiguration, opts v1.ApplyOptions) (result *networkprobev1beta1.NetworkProbe, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, networkProbe *applyconfigurationnetworkprobev1beta1.NetworkProbeApplyConfiguration, opts v1.ApplyOptions) (result *networkprobev1beta1.NetworkProbe, err error)
	NetworkProbeExpansion
}

// networkProbes implements NetworkProbeInterface
type networkProbes struct {
	*gentype.ClientWithListAndApply[*networkprobev1beta1.NetworkProbe, *networkprobev1beta1.NetworkProbeList, *applyconfigurationnetworkprobev1beta1.NetworkProbeApplyConfiguration]
}

// newNetworkProbes returns a NetworkProbes
func newNetworkProbes(c *K8sV1beta1Client, namespace string) *networkProbes {
	return &networkProbes{
		gentype.NewClientWithListAndApply[*networkprobev1beta1.NetworkProbe, *networkprobev1beta1.NetworkProbeList, *applyconfigurationnetworkprobev1beta1.NetworkProbeApplyConfiguration](
			"networkprobes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *networkprobev1beta1.NetworkProbe { return &networkprobev1beta1.NetworkProbe{} },
			func() *networkprobev1beta1.NetworkProbeList { return &networkprobev1beta1.NetworkProbeList{} },
		),
	}
}
