/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/networkprobe/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetworkProbeLister helps list NetworkProbes.
// All objects returned here must be treated as read-only.
type NetworkProbeLister interface {
	// List lists all NetworkProbes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.NetworkProbe, err error)
	// NetworkProbes returns an object that can list and get NetworkProbes.
	NetworkProbes(namespace string) NetworkProbeNamespaceLister
	NetworkProbeListerExpansion
}

// networkProbeLister implements the NetworkProbeLister interface.
type networkProbeLister struct {
	indexer cache.Indexer
}

// NewNetworkProbeLister returns a new NetworkProbeLister.
func NewNetworkProbeLister(indexer cache.Indexer) NetworkProbeLister {
	return &networkProbeLister{indexer: indexer}
}

// List lists all NetworkProbes in the indexer.
func (s *networkProbeLister) List(selector labels.Selector) (ret []*v1beta1.NetworkProbe, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.NetworkProbe))
	})
	return ret, err
}

// NetworkProbes returns an object that can list and get NetworkProbes.
func (s *networkProbeLister) NetworkProbes(namespace string) NetworkProbeNamespaceLister {
	return networkProbeNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NetworkProbeNamespaceLister helps list and get NetworkProbes.
// All objects returned here must be treated as read-only.
type NetworkProbeNamespaceLister interface {
	// List lists all NetworkProbes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.NetworkProbe, err error)
	// Get retrieves the NetworkProbe from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.NetworkProbe, error)
	NetworkProbeNamespaceListerExpansion
}

// networkProbeNamespaceLister implements the NetworkProbeNamespaceLister
// interface.
type networkProbeNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NetworkProbes in the indexer for a given namespace.
func (s networkProbeNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.NetworkProbe, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.NetworkProbe))
	})
	return ret, err
}

// Get retrieves the NetworkProbe from the indexer for a given namespace and name.
func (s networkProbeNamespaceLister) Get(name string) (*v1beta1.NetworkProbe, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("networkprobe"), name)
	}
	return obj.(*v1beta1.NetworkProbe), nil
}
