/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/ipreservation/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIPReservations implements IPReservationInterface
type FakeIPReservations struct {
	Fake *FakeK8sV1beta1
	ns   string
}

var ipreservationsResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1beta1", Resource: "ipreservations"}

var ipreservationsKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1beta1", Kind: "IPReservation"}

// Get takes name of the iPReservation, and returns the corresponding iPReservation object, and an error if there is any.
func (c *FakeIPReservations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.IPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipreservationsResource, c.ns, name), &v1beta1.IPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.IPReservation), err
}

// List takes label and field selectors, and returns the list of IPReservations that match those selectors.
func (c *FakeIPReservations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.IPReservationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipreservationsResource, ipreservationsKind, c.ns, opts), &v1beta1.IPReservationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.IPReservationList{ListMeta: obj.(*v1beta1.IPReservationList).ListMeta}
	for _, item := range obj.(*v1beta1.IPReservationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iPReservations.
func (c *FakeIPReservations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipreservationsResource, c.ns, opts))

}

// Create takes the representation of a iPReservation and creates it.  Returns the server's representation of the iPReservation, and an error, if there is any.
func (c *FakeIPReservations) Create(ctx context.Context, iPReservation *v1beta1.IPReservation, opts v1.CreateOptions) (result *v1beta1.IPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipreservationsResource, c.ns, iPReservation), &v1beta1.IPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.IPReservation), err
}

// Update takes the representation of a iPReservation and updates it. Returns the server's representation of the iPReservation, and an error, if there is any.
func (c *FakeIPReservations) Update(ctx context.Context, iPReservation *v1beta1.IPReservation, opts v1.UpdateOptions) (result *v1beta1.IPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipreservationsResource, c.ns, iPReservation), &v1beta1.IPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.IPReservation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIPReservations) UpdateStatus(ctx context.Context, iPReservation *v1beta1.IPReservation, opts v1.UpdateOptions) (*v1beta1.IPReservation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipreservationsResource, "status", c.ns, iPReservation), &v1beta1.IPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.IPReservation), err
}

// Delete takes name of the iPReservation and deletes it. Returns an error if one occurs.
func (c *FakeIPReservations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ipreservationsResource, c.ns, name), &v1beta1.IPReservation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIPReservations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipreservationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.IPReservationList{})
	return err
}

// Patch applies the patch and returns the patched iPReservation.
func (c *FakeIPReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.IPReservation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipreservationsResource, c.ns, name, pt, data, subresources...), &v1beta1.IPReservation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.IPReservation), err
}
